### ISSUE TITLE
How to manage everything.exe and services

### ISSUE THREAD

**Issue by melinyi** [sgrottel/EverythingSearchClient#14]
like this code

https://github.com/BookerLiu/GeekDesk/blob/7d3f1c9af056d3354e273c18faa1f509ea2bedea/Plugins/EveryThing/EveryThingUtil.cs#L28

**Comment by sgrottel** [comment]
Interesting Idea. This is currently not possible.

_I will not add functions to install/uninstall_ the Everything service. That is beyond scope of this library.

Querying the service's status, stopping, starting, and restarting are interesting extensions. I will add those functions.
